04-Jun-2024 17:28:53.942 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [hr.fer.zemris.java.p12.Inicijalizacija]
	java.lang.RuntimeException: java.sql.SQLException: Connections could not be acquired from the underlying database!
		at hr.fer.zemris.java.p12.Inicijalizacija.doesTableExist(Inicijalizacija.java:106)
		at hr.fer.zemris.java.p12.Inicijalizacija.createTableIfNotExists(Inicijalizacija.java:111)
		at hr.fer.zemris.java.p12.Inicijalizacija.contextInitialized(Inicijalizacija.java:60)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4463)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4911)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:687)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:659)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1014)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1866)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:816)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:468)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1584)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:312)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:903)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1345)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1335)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:876)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:470)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:951)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:735)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
		at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
		at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
		at hr.fer.zemris.java.p12.Inicijalizacija.doesTableExist(Inicijalizacija.java:100)
		... 41 more
	Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
		at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
		at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
		at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
		... 43 more
	Caused by: java.sql.SQLNonTransientConnectionException: java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.
		at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:74)
		at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:325)
		at org.apache.derby.client.ClientAutoloadedDriver.connect(ClientAutoloadedDriver.java:177)
		at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
		at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
		at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Caused by: ERROR 08001: java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.
		at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:150)
		at org.apache.derby.client.net.NetConnection.newAgent_(NetConnection.java:972)
		at org.apache.derby.client.am.ClientConnection.<init>(ClientConnection.java:361)
		at org.apache.derby.client.net.NetConnection.<init>(NetConnection.java:198)
		at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl.newNetConnection(ClientJDBCObjectFactoryImpl.java:278)
		at org.apache.derby.client.ClientAutoloadedDriver.connect(ClientAutoloadedDriver.java:170)
		... 9 more
	Caused by: java.net.ConnectException: Connection refused
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:589)
		at java.base/sun.nio.ch.Net.connect(Net.java:578)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:751)
		at java.base/java.net.Socket.connect(Socket.java:686)
		at java.base/java.net.Socket.<init>(Socket.java:555)
		at java.base/java.net.Socket.<init>(Socket.java:324)
		at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:267)
		at org.apache.derby.client.net.OpenSocketAction.run(OpenSocketAction.java:119)
		at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:144)
		... 14 more
04-Jun-2024 17:29:26.333 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [hr.fer.zemris.java.p12.Inicijalizacija]
	java.lang.RuntimeException: java.sql.SQLException: Connections could not be acquired from the underlying database!
		at hr.fer.zemris.java.p12.Inicijalizacija.doesTableExist(Inicijalizacija.java:106)
		at hr.fer.zemris.java.p12.Inicijalizacija.createTableIfNotExists(Inicijalizacija.java:111)
		at hr.fer.zemris.java.p12.Inicijalizacija.contextInitialized(Inicijalizacija.java:60)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4463)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4911)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:687)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:659)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1175)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1888)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1086)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:470)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1584)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:312)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:903)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1345)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1335)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:876)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:470)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:951)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:735)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
		at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
		at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
		at hr.fer.zemris.java.p12.Inicijalizacija.doesTableExist(Inicijalizacija.java:100)
		... 41 more
	Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
		at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
		at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
		at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
		... 43 more
	Caused by: java.sql.SQLNonTransientConnectionException: java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.
		at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:74)
		at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:325)
		at org.apache.derby.client.ClientAutoloadedDriver.connect(ClientAutoloadedDriver.java:177)
		at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
		at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
		at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
		at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
		at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
		at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
		at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
	Caused by: ERROR 08001: java.net.ConnectException : Error connecting to server localhost on port 1,527 with message Connection refused.
		at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:150)
		at org.apache.derby.client.net.NetConnection.newAgent_(NetConnection.java:972)
		at org.apache.derby.client.am.ClientConnection.<init>(ClientConnection.java:361)
		at org.apache.derby.client.net.NetConnection.<init>(NetConnection.java:198)
		at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl.newNetConnection(ClientJDBCObjectFactoryImpl.java:278)
		at org.apache.derby.client.ClientAutoloadedDriver.connect(ClientAutoloadedDriver.java:170)
		... 9 more
	Caused by: java.net.ConnectException: Connection refused
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:589)
		at java.base/sun.nio.ch.Net.connect(Net.java:578)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:751)
		at java.base/java.net.Socket.connect(Socket.java:686)
		at java.base/java.net.Socket.<init>(Socket.java:555)
		at java.base/java.net.Socket.<init>(Socket.java:324)
		at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:267)
		at org.apache.derby.client.net.OpenSocketAction.run(OpenSocketAction.java:119)
		at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:144)
		... 14 more
04-Jun-2024 17:29:26.571 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
04-Jun-2024 17:29:26.571 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
04-Jun-2024 17:29:26.573 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@48c7549e')
04-Jun-2024 19:50:18.881 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
04-Jun-2024 19:50:18.881 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
